### ISSUE TITLE
500 Inernal Server Error while inserting into a table via admin interface

### ISSUE THREAD

**Issue by pavdmyt** [jeffknupp/sandman2#34] opened 2016-04-05 09:24 UTC
Hi,

I'm using sandman2 with PostgreSQL.
Every time inserting data into a table using admin interface I'm receiving this page:

```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

However, table becomes updated and selects in `psql` shows new inserted data.

**Comment by jeffknupp** [comment] 2016-07-22 22:02
I'm not able to reproduce this. Can you give some more info?

**Comment by Datamance** [comment] 2016-08-03 04:52
I'm getting something somewhat similar with sandman2ctl:

```
[2016-08-02 21:29:13,086] ERROR in app: Exception on /admin/proposals/edit/ [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1643, in full_dispatch_request
    response = self.process_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1864, in process_response
    self.save_session(ctx.session, response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 926, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/sessions.py", line 359, in save_session
    val = self.get_signing_serializer(app).dumps(dict(session))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/itsdangerous.py", line 566, in dumps
    rv = self.make_signer(salt).sign(payload)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/itsdangerous.py", line 412, in sign
    return value + sep + self.get_signature(value)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/itsdangerous.py", line 347, in get_signature
    key = self.derive_key()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/itsdangerous.py", line 336, in derive_key
    mac = hmac.new(self.secret_key, digestmod=self.digest_method)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/hmac.py", line 42, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'int'
127.0.0.1 - - [02/Aug/2016 21:29:13] "POST /admin/proposals/edit/?url=%2Fadmin%2Fproposals%2F&id=a41e661c-db3d-44d6-8404-603e30a847ce HTTP/1.1" 500 -
```

**Comment by jeffknupp** [comment] 2016-08-03 19:28
Please try downloading version `0.1.0` from pypi and let me know if you see the same issue

**Comment by Datamance** [comment] 2016-08-06 19:48
@jeffknupp I can actually _edit_ records through the admin interface now, but I still get this error when I try to _insert_ a brand new record:

`sqlalchemy.exc.CompileError: Column 'proposals.id' is marked as a member of the primary key for table 'proposals', but **has no Python-side or server-side default generator indicated**, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.  Primary key columns typically may not store NULL.`

I actually created these tables with my own SQLAlchemy ORM classes using the following mixin:

```
class BaseEntityMixin(Timestamp):
    """The base model for every modeled entity."""

    @declared_attr
    def __tablename__(cls):
        return inflector.plural(cls.__name__.lower())

    id = Column(UUIDType, **default=uuid4**, primary_key=True)

    def __repr__(self):
        return '<{entity_type}-{id}>'.format(
            entity_type=self.__class__, id=self.id)
```

Once again, I'm guessing I'll have to extend sandman2.model.Model to make this work. Let me know if you think of any other solutions.

**Comment by jeffknupp** [comment] 2016-09-06 17:49
So the newest version of `sandman2` uses a version of SQLAlchemy still in beta (1.0.0b4 I think) that supports "scalar defaults" in the manner you want. Here's the documentation: http://docs.sqlalchemy.org/en/latest/changelog/migration_11.html#new-init-scalar-event-intercepts-default-values-at-orm-level

**Comment by jeffknupp** [comment] 2016-09-20 19:39
Closing as can not duplicate

**Closed by jeffknupp** 2016-09-20 19:39 UTC
Labels: invalid
